os:
  - windows
language: node_js
node_js:
  - 'node'
env:
  - YARN_GPG=no
install:
  - install.sh
script:
  - build.sh
deploy:
  message: 'Deploying with Firebase.'
  provider: firebase
  edge: true
after_deploy: yarn codechecks
