version: "3.8"

services:
  broker:
    image: redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - REDIS_URL=redis://broker:6379
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - broker
    stdin_open: true
    tty: true
