# Generated by Django 3.0.5 on 2020-04-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signimage',
            name='image_file',
            field=models.ImageField(upload_to='sign_images/'),
        ),
    ]
