# Generated by Django 3.0.5 on 2020-04-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0002_auto_20200410_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('video_file', models.FileField(upload_to='sign_videos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signword',
            name='videos',
            field=models.ManyToManyField(to='asl_dictionary.SignVideo'),
        ),
    ]
