# Generated by Django 3.0.5 on 2020-04-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0003_auto_20200410_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='signimage',
            name='alt_text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signvideo',
            name='alt_text',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
