# Generated by Django 3.0.5 on 2020-04-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0005_auto_20200412_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signword',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='signimage',
            name='alt_text',
            field=models.CharField(help_text='Textual representation of the image. Used by screen-readers and when the image is unavailable.', max_length=50),
        ),
        migrations.AlterField(
            model_name='signimage',
            name='caption',
            field=models.TextField(help_text='Displayed alongside the image.'),
        ),
        migrations.AlterField(
            model_name='signvideo',
            name='alt_text',
            field=models.CharField(help_text='Textual representation of the image. Used by screen-readers and when the image is unavailable.', max_length=50),
        ),
        migrations.AlterField(
            model_name='signvideo',
            name='caption',
            field=models.TextField(help_text='Displayed alongside the image.'),
        ),
    ]
