# Generated by Django 3.0.5 on 2020-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0006_auto_20200413_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signimage',
            name='alt_text',
            field=models.CharField(help_text='Textual representation of the image. Used by screen-readers and when the image is unavailable.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='signvideo',
            name='alt_text',
            field=models.CharField(help_text='Textual representation of the image. Used by screen-readers and when the image is unavailable.', max_length=50, unique=True),
        ),
    ]
