# Generated by Django 3.0.5 on 2020-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0007_auto_20200413_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='signword',
            name='see_also',
            field=models.ManyToManyField(blank=True, to='asl_dictionary.SignWord'),
        ),
    ]
