# Generated by Django 3.0.5 on 2020-04-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0008_signword_see_also'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signword',
            name='see_also',
            field=models.ManyToManyField(blank=True, related_name='_signword_see_also_+', to='asl_dictionary.SignWord'),
        ),
    ]
