# Generated by Django 3.0.5 on 2020-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0009_auto_20200413_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signimage',
            name='image_file',
            field=models.ImageField(help_text='GIFs should be uploaded as videos instead.', upload_to='sign_images/'),
        ),
        migrations.AlterField(
            model_name='signvideo',
            name='video_file',
            field=models.FileField(help_text='Will be converted to WebM format.', upload_to='sign_videos/'),
        ),
    ]
