# Generated by Django 3.0.5 on 2020-04-17 22:37

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ("asl_dictionary", "0010_auto_20200416_1830"),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name="signword",
            name="images",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True, help_text=None, to="asl_dictionary.SignImage"
            ),
        ),
        AlterSortedManyToManyField(
            model_name="signword",
            name="see_also",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True,
                help_text=None,
                related_name="_signword_see_also_+",
                to="asl_dictionary.SignWord",
            ),
        ),
        AlterSortedManyToManyField(
            model_name="signword",
            name="videos",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True, help_text=None, to="asl_dictionary.SignVideo"
            ),
        ),
    ]
