# Generated by Django 3.0.5 on 2020-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0011_auto_20200417_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideo',
            name='thumbnail_file',
            field=models.ImageField(blank=True, help_text='Will be automatically generated.', null=True, upload_to='sign_videos/thumbnails/'),
        ),
    ]
