# Generated by Django 3.0.5 on 2020-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0012_signvideo_thumbnail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideo',
            name='optimized_video_file',
            field=models.FileField(editable=False, null=True, upload_to='sign_videos/optimized/'),
        ),
    ]
