# Generated by Django 3.0.5 on 2020-04-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0013_signvideo_optimized_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signword',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
