# Generated by Django 3.0.5 on 2020-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0015_signword_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signword',
            name='description',
            field=models.TextField(blank=True, help_text='If not provided, the caption of the first image or video is shown on the card.', null=True),
        ),
    ]
