# Generated by Django 3.0.5 on 2020-06-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_dictionary', '0017_signvideo_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideo',
            name='is_sentence',
            field=models.BooleanField(default=False, help_text='Sentences are shown after definitions.', verbose_name='video is a sentence?'),
        ),
        migrations.AlterField(
            model_name='signimage',
            name='alt_text',
            field=models.CharField(help_text='Textual representation of the image or glossed ASL.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='signvideo',
            name='alt_text',
            field=models.CharField(help_text='Textual representation of the image or glossed ASL.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='signvideo',
            name='video_file',
            field=models.FileField(help_text='Will be compressed automatically.', upload_to='sign_videos/'),
        ),
    ]
