version: 2.1

orbs:
  node: circleci/node@3.0.1
  browser-tools: circleci/browser-tools@1.0.1
  # heroku: circleci/heroku@1.2.0

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.cache/yarn
            - .node_modules
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

executors:
  frontend-executor:
    docker:
      - image: "circleci/node:latest"
  backend-executor:
    docker:
      - image: "cimg/base:2020.01"

jobs:
  checkout-project:
    executor: frontend-executor
    working_directory: ~/asl-dictionary
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  build:
    executor: frontend-executor
    working_directory: ~/asl-dictionary/frontend
    steps:
      - attach_workspace:
          at: ~/asl-dictionary
      - node/install:
          install-yarn: true
          node-version: latest
      - restore_cache_cmd
      - run: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache_cmd
      - run: yarn generate
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - firebase.json
            - .firebaserc
            - firestore.rules
            - firestore.indexes.json
            - lighthouserc.js

  deploy:
    executor: frontend-executor
    working_directory: ~/asl-dictionary/frontend
    steps:
      - attach_workspace:
          at: ~/asl-dictionary/frontend
      - run: sudo npm install -g firebase-tools
      - run:
          name: Firebase Deploy
          command: firebase deploy --token "$FIREBASE_TOKEN"
  lighthouse:
    executor: frontend-executor
    working_directory: ~/asl-dictionary/frontend
    steps:
      - attach_workspace:
          at: ~/asl-dictionary/frontend
      - run: sudo npm install -g @lhci/cli@0.4.x
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: lhci autorun

  heroku_deploy:
    executor: backend-executor
    working_directory: ~/asl-dictionary/backend
    steps:
      - attach_workspace:
          at: ~/asl-dictionary
      # - heroku/install
      - run: git init
      - run: git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
      - run: git add .
      - run: git config --global user.email "CircleCI@circleci.com"
      - run: git config --global user.name "CircleCI"
      - run: git commit -m "Deploy from CircleCI"
      - run: git push heroku master --force
      # - heroku/deploy-via-git

workflows:
  frontend:
    jobs:
      - checkout-project
      - build:
          requires:
            - checkout-project
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - lighthouse:
          requires:
            - build
  backend:
    jobs:
      - checkout-project
      - heroku_deploy:
          requires:
            - checkout-project
          filters:
            branches:
              only: master
