version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/asl-dictionary
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: 
            working_directory: ~/asl-dictionary/frontend
            command:
              npm install -g @lhci/cli@0.4.x
              yarn generate
              lhci autorun

workflows:
  main:
    jobs:
      - build
