version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: cd frontend
      - run: yarn --frozen-lockfile

workflows:
  main:
    jobs:
      - build
