version: 2.1

orbs:
  node: circleci/node@3.0.1
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/asl-dictionary
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      # Download and cache dependencies
      # - restore_cache:
          # keys:
            # - v1-dependencies-{{ checksum "package.json" }}
            # - v1-dependencies-
      - run: 
          working_directory: ~/asl-dictionary/frontend
          command: yarn --frozen-lockfile
      # - save_cache:
          # key: v1-npm-deps-{{ checksum "package-lock.json" }}
          # paths:
            # - ./node_modules
      - run: 
          working_directory: ~/asl-dictionary/frontend
          command: yarn generate
      # - run: 
          # working_directory: ~/asl-dictionary/frontend
          # command: sudo npm install -g firebase-tools
      # - run:
          # name: Firebase Deploy
          # command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
          # when: 
            # - equal: [ master, << pipeline.git.branch >> ]
      - run: sudo npm install -g @lhci/cli@0.4.x
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: lhci autorun
  

workflows:
  main:
    jobs:
      - build
      # - deploy
