version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: latest
      - run: node --version

workflows:
  main:
    jobs:
      - build
