name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --without dev
      # - name: Run Tests
      #   run: |
      #     python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2

      - name: Lint Terraform
        id: fmt
        run: terraform fmt -check

      - name: Plan
        id: plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        working-directory: backend/terraform/environments/dev
        run: |
          terraform init
          terraform plan -out=tfplan

      - name: Run Deploy
        if: github.ref == 'refs/heads/master'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        working-directory: backend/terraform/environments/dev
        run: |
          terraform apply tfplan
